controller_manager:
  ros__parameters:
    update_rate: 100
    # Need to turn off the sim_time if using real robot
    # use_sim_time: true

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    simple_velocity_controller:
      type: velocity_controllers/JointGroupVelocityController

simple_velocity_controller:
  ros__parameters:
    # List the joints in the EXACT order your C++ code expects 
    # (Index 0 = Right, Index 1 = Left based on your read/write logic)
    joints:
      - wheel_right_joint
      - wheel_left_joint